config/routes.rb
Rails.application.routes.draw do
  resources :musics

root 'musics#all'

end

app/models/music.rb
class Music < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]

  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url, notice: 'Music was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:name, :format, :length, :size)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  <title>Musicmanager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track', 'sorttable' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
	<nav class="navbar navbar-default" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Music Manager", "https://saisoundmanager.herokuapp.com", class: "navbar-brand" %>
            <!--<a class="navbar-brand" href="http://localhost:3000">Music Manager</a> -->
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "New Music", new_music_path%></li>
              <li><%= link_to "All Music", musics_path%></li>
              <li><%= link_to "Contact", "https://www.linkedin.com/in/saipathyam"%></li>
            </ul>
          </div><!--/.nav-collapse -->
           </div><!--/.container-fluid -->
      </nav>
<div class="container">
	<%= yield %>
</div>
 
</body>
  
       
</html>

app/views/musics/_form.html.erb
<%= simple_form_for(@music, html: {class: "form-horizontal"}) do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% @music.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="navbar form-signin well">
    <%= f.input :name, placeholder: 'Music Name' %>
    <%= f.input :format,placeholder: 'Mp3,Mp4,..etc..' %>
    <%= f.input :length, placeholder: 'HH:MM:SS' %>
    <%= f.input :size, placeholder: 'Mb,Gb' %>
    <%= f.button :submit %>
  </div>
  <div class="container">
    </div>
<% end %>

app/views/musics/all.html.erb
<!doctype HTML>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="assets/css/bootstrap-responsive.css" rel="stylesheet"></head>
<div class="ri jumbotron">
<%= link_to image_tag("music.jpg", class: "container"), new_music_path%>
</div>

app/views/musics/edit.html.erb
<h1>Editing Music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music, class: "btn btn-default btn-xs" %>
<%= link_to 'Back', musics_path, class: "btn btn-default btn-xs" %>

app/views/musics/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
<h1>Music List!!!</h1>
</div>
<div class="col-md-6">
<table class="table table-striped sortable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Format</th>
      <th>Length</th>
      <th>Size</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |music| %>
      <tr>
        <td><strong><%= music.name %></strong></td>
        <td><%= music.format %></td>
        <td><%= music.length %></td>
        <td><%= music.size %></td>
        <div class="meta">
        <td><%= link_to 'Details', music %></td>
        <div class="musics">
          <span class="admin">
            <td><%= link_to 'Edit', edit_music_path(music) %></td> 
            <td><%= link_to 'Delete', music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </span>
        </div>
      </div>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

</div>

app/views/musics/new.html.erb
<h1>New Music</h1>

<%= render 'form' %>
<%= link_to 'Back', musics_path, class: "btn btn-default" %>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>
<div >
    <div class="col-sm-4" >
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Music Details</h3>
            </div>
            <div class="panel-body">
              <p>
              	<strong>Name:</strong>
              	<%= @music.name %>
              </p>
              <p>
              	<strong>Format:</strong>
              	<%= @music.format %>
              </p>
              <p>
                <strong>Length:</strong>
                <%= @music.length %>
            </p>
            <p>
              <strong>Size:</strong>
              <%= @music.size %>
          </p>
            </div>
          </div>
          <%= link_to 'Edit', edit_music_path(@music), class: "btn btn-default btn-xs" %>
<%= link_to 'Back', musics_path, class: "btn btn-default btn-xs" %>
        </div>


</div>